import Head from 'next/head'
import Navbar from '../components/home/Navbar'
export default function Home() {
  return (
    <>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className='text-red-500'>hi</h1>
        <Navbar />
      </main>
    </>
  )
}
