import Head from 'next/head'
import Navbar from '../components/home/Navbar'
import Landing from '@/components/home/Landing'
import Features from '@/components/home/Features'
import Services from '@/components/home/Services'
import Contact from '@/components/home/Contact'
import Vendor from '@/components/home/Vendor'
export default function Home() {
  return (
    <>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </Head>
      <main className='bg-[#eee] min-h-screen'>
        <Navbar />
        <Landing/>
        <Features/>
        <Services/>
        <Vendor/>
        <Contact/>
      </main>
    </>
  )
}
